{{- if .Values.app.nginx.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nginx-configmap
data:
  wger-app.conf: |
    upstream app_server {
      server localhost:8000 max_fails=1 fail_timeout=10s;
      zone upstreams 64K;
      keepalive 2;
    }

    server {
      listen 8080;
      client_max_body_size 4G;

      # set the correct host(s) for your site
      server_name {{ join " " .Values.ingress.url }};

      access_log /var/log/nginx/access.log combined;
      error_log  /var/log/nginx/error.log warn;

      # path for static files (only needed for serving "local" static and media files)
      root /var/www/html/;

      location / {
        # checks for static file, if not found proxy to app
        try_files $uri @proxy_to_app;
      }

      location @proxy_to_app {
        proxy_http_version 1.1;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        {{- if .Values.ingress.tls }}
        proxy_set_header X-Forwarded-Proto https;
        {{- else }}
        proxy_set_header X-Forwarded-Proto $scheme;
        {{- end }}
        proxy_set_header Host $http_host;

        # keep alive
        proxy_set_header   "Connection" "";

        # https://www.getpagespeed.com/server-setup/nginx/tuning-proxy_buffer_size-in-nginx
        proxy_buffer_size 16k;
        proxy_busy_buffers_size 24k; # essentially, proxy_buffer_size + 2 small buffers of 4k
        proxy_buffers 64 4k;
        proxy_max_temp_file_size 0;

        # send 500 when timeout
        proxy_next_upstream error timeout http_500;

        proxy_redirect off;
        proxy_pass http://app_server;
      }

      error_page 500 502 503 504 /500.html;
      location = /500.html {
        root /var/www/html/;
      }
    }
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: wger-pg-init
data:
  40-grantSuperuser.sql: |
    ALTER USER {{ .Values.postgres.userDatabase.name }} WITH SUPERUSER;
