{{- if .Values.app.nginx.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nginx-configmap
data:
  wger-app.conf: |
    upstream app_server {
      server localhost:8000 fail_timeout=0;
    }

    server {
      listen 8080;
      client_max_body_size 4G;

      # set the correct host(s) for your site
      server_name {{ join " " .Values.ingress.url }};

      access_log /var/log/nginx/access.log combined;
      error_log  /var/log/nginx/error.log warn;

      keepalive_timeout 5;

      # path for static files (only needed for serving "local" static and media files)
      root /var/www/html/;

      location / {
        # checks for static file, if not found proxy to app
        try_files $uri @proxy_to_app;
      }

      location @proxy_to_app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;

        proxy_redirect off;
        proxy_pass http://app_server;
      }

      error_page 500 502 503 504 /500.html;
      location = /500.html {
        root /var/www/html/;
      }
    }
{{- end }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: wger-pg-init
data:
  grantSuperuser.sql: |
    ALTER USER {{ .Values.postgres.userDatabase.name }} WITH SUPERUSER;
